FROM node:16-alpine AS node
WORKDIR /app
COPY ./ ./
RUN npm install --legacy-peer-deps
RUN npm run build --configuration=dev

FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY --from=node ./app/dist/management_app /usr/share/nginx/html
EXPOSE 80