version: '3.8'

services:
  # Executa uma instância do Mosquitto para os sensores IoT.
  mosquitto:
    image: eclipse-mosquitto:1.5.5
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - 1883
    ports:
      - "1883:1883"
    networks:
      - infra_network
    volumes:
      - ./mosquitto_dev/config/:/mosquitto/config/
      - ./mosquitto_dev/data/:/mosquitto/data/
      
  kafka:
    image: docker.io/bitnami/kafka:3.7
    container_name: kafka
    ports:
      - '9094:9094'
    expose:
      - 9094
    volumes:
      - "./kafka_data_dev:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - infra_network

  # Executa instância do MongoDB para salvar os dados.
  mongodb:
    image: mongo:4.0.5
    hostname: mongodb
    container_name: mongodb
    restart: always
    expose:
      - 27017
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: smartlabRoot
      MONGO_INITDB_ROOT_PASSWORD: smartlabRoot2022
    volumes:
      - ./mongodb_dev:/data/db
    networks:
      - infra_network

  # Instância do Mongo Express para visualização dos dados.
  mongo-express:
    image: mongo-express
    hostname: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_USERNAME=smartlabRoot
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=smartlabRoot2022
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=dev
    depends_on:
      - mongodb
    ports:
      - "8888:8081"
    expose:
      - 8888
    networks:
      - infra_network

  # Instância em execução do postgresql.
  postgresql:
    image: postgres:14.2-alpine
    hostname: postgresql-management
    container_name: postgresql-management
    restart: always
    environment:
      POSTGRES_USER: SMARTLAB_USER
      POSTGRES_PASSWORD: SMARTLAB_123456
      POSTGRES_DB: SMARTLAB_DB
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./postgres_dev/data:/var/lib/postgresql/data
    networks:
      - infra_network

  # Define a configuração da API.
  management-api:
    image: management-dashboard-api:1.0.0
    build:
      context: ./management_api
      dockerfile: Dockerfile.dev
    container_name: management_dash_api
    ports:
      - "8071:8080"
    expose:
      - 8071
    depends_on:
      - kafka
      - postgresql
    networks:
      - infra_network

  # Define a configuração da aplicação.
  management-app:
    image: management-dashboard-app:1.0.0
    build:
      context: ./management_app
      dockerfile: Dockerfile.dev
    container_name: management_dash_app
    ports:
      - "4071:80"
    expose:
      - 4071
    depends_on:
      - kafka
      - postgresql
    networks:
      - infra_network

  # Executa o Servico de controle das medicoes.     
  stream-control-service:
    image: stream-control-service:1.0.0
    build:
      context: ./stream-control-service
      dockerfile: Dockerfile.dev
    container_name: service_stream_control
    ports:
      - "8171:8080"
    expose:
      - 8171
    depends_on:
      - kafka
      - mongodb
    networks:
      - infra_network

  # Define a configuração da bridge entre mqtt e kafka.
  mqtt-kafka-bridge:
    image: mqtt-kafka-bridge:1.0.0
    build: 
      context: ./mqtt-kafka-bridge
      dockerfile: Dockerfile.dev
    container_name: mqtt-kafka-bridge
    ports:
      - "8012:8080"
    expose:
      - 8012
    depends_on:
      - kafka
      - mongodb
      - mosquitto
    networks:
      - infra_network

  # Define a configuração da bridge entre kafka e mqtt.
  kafka-mqtt-bridge:
    image: kafka-mqtt-bridge:1.0.0
    build:
      context: ./kafka-mqtt-bridge
      dockerfile: Dockerfile.dev
    container_name: kafka-mqtt-bridge
    ports:
      - "8013:8080"
    expose:
      - 8013
    depends_on:
      - kafka
      - mongodb
      - mosquitto
    networks:
      - infra_network

networks:
  infra_network:
    name: infra_network
    driver: bridge