spring:
  application:
    name: Management API Desenv
  datasource:
    url: jdbc:postgresql://postgresql-management:5432/SMARTLAB_DB
    username: SMARTLAB_USER
    password: SMARTLAB_123456
  kafka:
    bootstrap-servers: kafka:9092
    client-id: management-api-dev

smartlab:
  app:
    jwtSecret: eyJhbGciOiJIUzI1NiJ9seyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcxODcyMzQ1NywiaWF0IjoxNzE4NzIzNDU3fQrFcQWRdvspKteiRgmmUAIiwbh7fLL0KZfU8baSfw2mjE
    jwtExpirationMs: 3600000