services:
  # Define a configuração da aplicação.
  management-app:
    image: management-dashboard-app:1.0.0
    build:
      context: ./management_app
      dockerfile: Dockerfile
    container_name: management-dash-app
    ports:
      - 4200:80
    networks:
      - app_infra_network

  # Define a configuração da API.
  management-api:
    image: management-api:1.0.0
    build:
      context: ./management_api
      dockerfile: Dockerfile
    container_name: management-dash-api
    ports:
      - 8010:8080
    networks:
      - app_infra_network

  # Executa o Servico de controle das medicoes.     
  stream-control-service:
    image: stream-control-service:1.0.0
    build:
      context: ./stream-control-service
      dockerfile: Dockerfile
    container_name: service-stream-control
    ports:
      - 8011:8080
    networks:
      - app_infra_network

  # Define a configuração da bridge entre mqtt e kafka.
  mqtt-kafka-bridge:
    image: mqtt-kafka-bridge:1.0.0
    build: 
      context: ./mqtt-kafka-bridge
      dockerfile: Dockerfile
    container_name: mqtt-kafka-bridge
    ports:
      - "8012:8080"
    expose:
      - 8012
    networks:
      - app_infra_network

  # Define a configuração da bridge entre kafka e mqtt.
  kafka-mqtt-bridge:
    image: kafka-mqtt-bridge:1.0.0
    build:
      context: ./kafka-mqtt-bridge
      dockerfile: Dockerfile
    container_name: kafka-mqtt-bridge
    ports:
      - 8013:8080
    networks:
      - app_infra_network

networks:
  app_infra_network:
    name: infra_network
    external: true
