spring:
  application:
    name: Service - Stream Control Dev
  data:
    mongodb:
      host: localhost
      port: 27017
      username: smartlabRoot
      password: smartlabRoot2022
      database: smartlab
  kafka:
    bootstrap-servers: localhost:9094
    group-id: lab-stream-control
server:
  port: 8081