spring:
  application:
    name: Service - Stream Control Prod
  data:
    mongodb:
      host: 10.1.3.73
      port: 2773
      username: smartlabRoot
      password: smartlabRoot2022
      database: smartlab
  kafka:
    bootstrap-servers: 10.1.3.73:9073
    group-id: scs-prod
    consumer:
      bootstrap-servers: 10.1.3.73:9073
      group-id: icmc-prod
    producer:
      bootstrap-servers: 10.1.3.73:9073
server:
  port: 8080